#!/usr/bin/env python3
"""
Batch Execution Script - TURBO
===============================

Runs all TURBO backtest scripts, report generators, and verification in optimized order.
Groups operations to minimize redundant computations.

Execution Order:
1. Core backtest (generates CSV files for both PROD & TURBO)
2. Visualization generators (uses CSV files)
3. Report generators (uses CSV files)
4. Integration verification (validates everything)

Usage:
    python run_all_batch.py
"""

import subprocess
import sys
from pathlib import Path
from datetime import datetime


def run_script(script_name, description):
    """Run a Python script and report status."""
    print(f"\n{'='*80}")
    print(f"Running: {description}")
    print(f"Script: {script_name}")
    print(f"{'='*80}\n")
    
    try:
        result = subprocess.run(
            [sys.executable, script_name],
            capture_output=True,
            text=True,
            timeout=600  # 10 minute timeout (TURBO needs more time for enhanced viz)
        )
        
        # Print output
        if result.stdout:
            print(result.stdout)
        
        if result.returncode != 0:
            print(f"\n❌ FAILED with exit code {result.returncode}")
            if result.stderr:
                print(f"Error output:\n{result.stderr}")
            return False
        else:
            print(f"\n✅ SUCCESS")
            return True
            
    except subprocess.TimeoutExpired:
        print(f"\n❌ TIMEOUT - Script took longer than 10 minutes")
        return False
    except Exception as e:
        print(f"\n❌ ERROR: {str(e)}")
        return False


def main():
    """Run all scripts in optimized batch order."""
    print("\n" + "="*80)
    print("TURBO FOLDER - BATCH EXECUTION")
    print("="*80)
    print(f"Start Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"Working Directory: {Path.cwd()}")
    
    results = {}
    
    # =========================================================================
    # PHASE 1: Core Backtest (Generates all CSV files - PROD & TURBO)
    # =========================================================================
    print("\n" + "="*80)
    print("PHASE 1: CORE BACKTEST (PROD vs TURBO)")
    print("="*80)
    
    success = run_script(
        "rsi_calendar_date_backtest.py",
        "PROD vs TURBO Backtest - Generates equity CSVs & enhanced visualizations"
    )
    results["Core Backtest"] = success
    
    if not success:
        print("\n❌ Core backtest failed - cannot continue")
        return False
    
    # =========================================================================
    # PHASE 2: Additional Visualizations (Uses CSV files from Phase 1)
    # =========================================================================
    print("\n" + "="*80)
    print("PHASE 2: ADDITIONAL VISUALIZATIONS")
    print("="*80)
    
    viz_scripts = [
        ("generate_cash_pool_visualization.py", "Cash Pool Visualization"),
        ("generate_rsi_timeline_chart.py", "RSI Timeline Chart"),
    ]
    
    for script, desc in viz_scripts:
        if Path(script).exists():
            success = run_script(script, desc)
            results[desc] = success
        else:
            print(f"⚠️  {script} not found - skipping")
            results[desc] = None
    
    # Enhanced visualizations (if they need to be run separately)
    if Path("enhanced_visualizations.py").exists():
        print("\n⚠️  enhanced_visualizations.py found")
        print("   Note: Enhanced visualizations should be generated by main backtest")
        print("   Skipping separate run")
        results["Enhanced Visualizations"] = None
    
    # =========================================================================
    # PHASE 3: Variant Comparisons (if exists)
    # =========================================================================
    print("\n" + "="*80)
    print("PHASE 3: VARIANT COMPARISONS")
    print("="*80)
    
    if Path("rsi_variants_backtest.py").exists():
        success = run_script(
            "rsi_variants_backtest.py",
            "Strategy Variant Comparisons"
        )
        results["Variant Comparisons"] = success
    else:
        print("⚠️  rsi_variants_backtest.py not found - skipping")
        results["Variant Comparisons"] = None
    
    # =========================================================================
    # PHASE 4: Integration Verification (Validates all outputs)
    # =========================================================================
    print("\n" + "="*80)
    print("PHASE 4: INTEGRATION VERIFICATION")
    print("="*80)
    
    success = run_script(
        "verify_integration.py",
        "Integration Verification - Data Flow Check"
    )
    results["Integration Verification"] = success
    
    # =========================================================================
    # FINAL SUMMARY
    # =========================================================================
    print("\n" + "="*80)
    print("BATCH EXECUTION SUMMARY")
    print("="*80)
    print(f"End Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    print("\nResults:")
    for task, status in results.items():
        if status is True:
            print(f"   ✅ {task}")
        elif status is False:
            print(f"   ❌ {task}")
        else:
            print(f"   ⚠️  {task} (skipped)")
    
    # Count results
    passed = sum(1 for s in results.values() if s is True)
    failed = sum(1 for s in results.values() if s is False)
    skipped = sum(1 for s in results.values() if s is None)
    
    print(f"\nSummary: {passed} passed, {failed} failed, {skipped} skipped")
    
    # List generated files
    print("\n" + "="*80)
    print("GENERATED FILES")
    print("="*80)
    
    expected_files = [
        "equity_prod_rainy_calendar_dates.csv",
        "equity_turbo_rainy_calendar_dates.csv",
        "rainy_buys_prod_calendar_dates.csv",
        "rainy_buys_turbo_calendar_dates.csv",
        "yearly_prod_vs_turbo.csv",
        "rainy_amounts_timeseries.csv",
        "strategy_comparison_prod_vs_turbo.png",
        "yearly_prod_vs_turbo.png",
        "rainy_amount_over_time_prod_vs_turbo.png",
        "dashboard_interactive_turbo.png",
        "regime_performance_turbo.png",
        "monte_carlo_cash_pool_turbo.png",
        "consecutive_rainy_heatmap_turbo.png",
    ]
    
    for filename in expected_files:
        filepath = Path(filename)
        if filepath.exists():
            size_kb = filepath.stat().st_size / 1024
            print(f"   ✅ {filename} ({size_kb:.1f} KB)")
        else:
            print(f"   ⚠️  {filename} (not found)")
    
    if failed > 0:
        print("\n❌ BATCH EXECUTION FAILED")
        return False
    else:
        print("\n✅ BATCH EXECUTION SUCCESSFUL")
        return True


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
